version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      next:
        patterns: ["next", "eslint-config-next"]
      react-ecosystem:
        patterns: ["react*", "@types/react*"]
